#!/bin/sh
#
# Set up a chroot environment based on Debian Sarge, for building.
#
# By building based on binaries from a very old version, all recent
# versions can be supported.

MIRROR=http://archive.debian.org/debian-archive/debian
RELEASE=sarge

if [ $# = 0 ]; then
	echo "Usage: $0 <dest dir>"
	exit 1
fi

dest_dir="$1"

add_pkg() {
	if [ ".$pkgs" = "." ]; then
		pkgs="$1"
	else
		pkgs="$pkgs,$1"
	fi
}

pkgs=""

# Basic packages for C build:
add_pkg gcc
add_pkg make

# Chocolate Doom dependencies:
add_pkg automake1.8
add_pkg autoconf
add_pkg libtool
add_pkg libsdl1.2-dev
add_pkg libsdl-mixer1.2-dev
add_pkg libsdl-net1.2-dev
add_pkg python-imaging

# Needed for svn checkout
add_pkg subversion

# Packages for debian package build:
add_pkg debhelper
add_pkg dpkg-dev
add_pkg cdbs

# Basic convenience packages:
add_pkg vim-full
add_pkg less

debootstrap "--include=$pkgs" "$RELEASE" "$dest_dir" "$MIRROR"

