#!/bin/sh
#
# Set up a chroot environment based on Debian Sarge, for building.
#
# By building based on binaries from a very old version, all recent
# versions can be supported.

MIRROR=http://archive.debian.org/debian-archive/debian
RELEASE=sarge

if [ $# = 0 ]; then
	echo "Usage: $0 <dest dir>"
	exit 1
fi

dest_dir="$1"

add_pkg() {
	if [ ".$pkgs" = "" ]; then
		pkgs="$1"
	else
		pkgs="$pkgs,$1"
	fi
}

pkgs=""

add_pkg gcc
add_pkg make
add_pkg automake1.8
add_pkg autoconf
add_pkg libsdl1.2-dev
add_pkg libsdl-mixer1.2-dev
add_pkg libsdl-net1.2-dev
add_pkg python-imaging
add_pkg subversion

debootstrap "--include=$pkgs" "$RELEASE" "$dest_dir" "$MIRROR"

